spring:
  application:
    name: liu-ai-mother-backend
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  group-configs:
    - group: "default"
      packages-to-scan: com.liu.liuaicodemother.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
