spring:
  application:
    name: liu-ai-mother-backend
  profiles:
    active: local
  session:
    store-type: redis
    timeout: 2592000
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

springdoc:
  group-configs:
    - group: "default"
      packages-to-scan: com.liu.liuaicodemother.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
